"""Table: training budget per learner in millions of environment steps (generated/tables/budget.tex)."""
import sys

from common import ROOT, VENUE_DIR, train_steps

sys.path.insert(0, str(ROOT))
from drone_autonomy.methods import ITERS  # noqa: E402

COLS = [("dr", "DR"), ("maml", "MAML fam."), ("reptile", "Reptile"), ("pearl", "PEARL"), ("rl2", "RL$^2$")]
ROWS = [("tracking_residual", "C1 residual"), ("tracking_gains", "C2 gains"), ("navigation", "C3 planner$^*$")]


def main():
    out = ["% generated by figures_scripts/budget_table.py; do not edit", "\\begin{tabular}{@{}lrrrrr@{}}", "\\toprule",
           "Combination & " + " & ".join(c for _, c in COLS) + " \\\\", "\\midrule"]
    for problem, label in ROWS:
        cells = []
        for m, _ in COLS:
            cells.append("%.1f" % (train_steps(problem, m, ITERS[problem][m]) / 1e6) if m in ITERS[problem] else "--")
        out.append(label + " & " + " & ".join(cells) + " \\\\")
    out += ["\\bottomrule", "\\multicolumn{6}{@{}l}{$^*$MAML family and Reptile: additional steps after starting from DR.}",
            "\\end{tabular}"]
    p = VENUE_DIR / "generated" / "tables" / "budget.tex"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
