"""Table III: navigation results, privileged planner and full stack (generated/tables/navigation.tex)."""
import sys

from common import LABEL, ROOT, VENUE_DIR, summary

sys.path.insert(0, str(ROOT))
from drone_autonomy.benchmark import FULLSTACK_TASKS, N_TASKS  # noqa: E402

METHODS = ["classical", "classical_l1", "dr", "dr_finetune", "e2e_dr", "e2e_dr_finetune",
           "maml", "fomaml", "anil", "metasgd", "reptile", "pearl", "rl2"]
GROUP = {"classical": "Classical", "dr": "Non-meta learned", "maml": "Gradient meta-learning (warm-started)",
         "pearl": "Context meta-learning (from scratch)"}
COLS = [("test_pre", False), ("test_post", False), ("test_collision", True),
        ("full_test_success_pre", False), ("full_test_success_post", False), ("full_test_collision_post", True),
        ("ood_post", False)]


def main():
    nv = {r["method"]: r for r in summary()["navigation"]}
    best = [(min if low else max)(nv[m][k] for m in METHODS) for k, low in COLS]
    out = ["% generated by figures_scripts/navigation_table.py; do not edit",
           "\\begin{tabular}{@{}llrrrrrrr@{}}", "\\toprule",
           " & & \\multicolumn{3}{c}{Privileged planner (%d rooms)} & \\multicolumn{3}{c}{Full stack (%d rooms)} & OOD \\\\"
           % (N_TASKS["navigation"] * 4, FULLSTACK_TASKS["test"]),
           "\\cmidrule(lr){3-5}\\cmidrule(lr){6-8}",
           "Method & Data & Before & After & Coll. & Before & After & Coll. & After \\\\",
           " & (ep.) & (\\%) & (\\%) & (\\%) & (\\%) & (\\%) & (\\%) & (\\%) \\\\", "\\midrule"]
    for m in METHODS:
        if m in GROUP:
            out.append("\\multicolumn{9}{@{}l}{\\emph{%s}} \\\\" % GROUP[m])
        r = nv[m]
        cells = []
        for (k, low), b in zip(COLS, best):
            txt = "%d" % round(100 * r[k])
            cells.append("\\textbf{%s}" % txt if abs(r[k] - b) < 1e-12 else txt)
        data = r.get("test_episodes", 0)
        out.append("%s & %s & %s \\\\" % (LABEL[m], data, " & ".join(cells)))
    out += ["\\bottomrule", "\\end{tabular}"]
    path = VENUE_DIR / "generated" / "tables" / "navigation.tex"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
