"""Table V: navigation adaptation vs inner step size and data budget (idea I-02 experiment)."""
import json

from common import HERE, VENUE_DIR

EXP = HERE.parent / "ideas" / "experiments" / "02_nav_step_size" / "results"
ROWS = [("maml", 1.0, 10, "MAML, meta-trained step"), ("maml", 0.3, 10, "MAML, step $\\times$0.3"),
        ("maml", 0.1, 10, "MAML, step $\\times$0.1"), ("maml", 1.0, 30, "MAML, 30 ep./stage"),
        ("metasgd", 1.0, 10, "Meta-SGD, learned steps"), ("metasgd", 0.3, 10, "Meta-SGD, steps $\\times$0.3"),
        ("metasgd", 0.1, 10, "Meta-SGD, steps $\\times$0.1")]


def load(m, s, E):
    return json.loads((EXP / f"{m}_scale{s}_E{E}.json").read_text())


def main():
    out = ["% generated by figures_scripts/step_size_table.py; do not edit", "\\begin{tabular}{@{}lrrrrr@{}}", "\\toprule",
           " & \\multicolumn{4}{c}{Success by stage (\\%)} & Coll. \\\\", "\\cmidrule(lr){2-5}",
           "Configuration & 0 & 1 & 2 & 3 & (\\%) \\\\", "\\midrule"]
    for m, s, E, label in ROWS:
        d = load(m, s, E)
        out.append("%s & %s & %d \\\\" % (label, " & ".join("%d" % round(100 * v) for v in d["success"]),
                                          round(100 * d["collision"][-1])))
    out += ["\\bottomrule", "\\end{tabular}"]
    path = VENUE_DIR / "generated" / "tables" / "stepsize.tex"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
