"""Table I: the task distribution (generated/tables/tasks.tex), read from drone_autonomy/tasks.py."""
import sys

from common import ROOT, VENUE_DIR

sys.path.insert(0, str(ROOT))
from drone_autonomy.tasks import RANGES  # noqa: E402

ROWS = [("mass_scale", "Payload (mass scale)", "$\\times$", 1, "%.2f"),
        ("motor_eff_min", "Weakest motor efficiency", "\\%", 100, "%d"),
        ("drag_scale", "Drag scale", "$\\times$", 1, "%.1f"),
        ("wind_speed", "Steady wind", "m/s", 1, "%.1f"),
        ("gust_std", "Gust std.\\ (OU, 0.5 s)", "m/s", 1, "%.1f"),
        ("latency_steps", "Command latency", "ms", 10, "%d")]


def main():
    out = ["% generated by figures_scripts/task_table.py; do not edit", "\\begin{tabular}{@{}llll@{}}", "\\toprule",
           "Parameter & Unit & Train / held-out & OOD \\\\", "\\midrule"]
    for key, name, unit, scale, fmt in ROWS:
        (a, b), (c, d) = RANGES[key]
        rng = lambda lo, hi: (fmt % (lo * scale)) + "--" + (fmt % (hi * scale))
        out.append("%s & %s & %s & %s \\\\" % (name, unit, rng(a, b), rng(c, d)))
    out += ["\\bottomrule", "\\end{tabular}"]
    path = VENUE_DIR / "generated" / "tables" / "tasks.tex"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
