"""Table II: tracking results for the residual and gain-tuning combinations (generated/tables/tracking.tex)."""
from common import LABEL, ORDER, VENUE_DIR, summary

METHODS = ["classical", "l1", "dr", "dr_finetune", "maml", "fomaml", "anil", "metasgd", "reptile", "pearl", "rl2"]
GROUP = {"classical": "Classical", "dr": "Non-meta learned", "maml": "Gradient meta-learning", "pearl": "Context meta-learning"}


def main():
    s = {p: {r["method"]: r for r in summary()[p]} for p in ("tracking_residual", "tracking_gains")}
    res, gain = s["tracking_residual"], s["tracking_gains"]
    cols = [  # (dict, key, lower_is_better, formatter)
        (res, "test_pre", True), (res, "test_post", True), (res, "ood_post", True), (res, "ood_crash", True),
        (gain, "test_pre", True), (gain, "test_post", True), (gain, "ood_post", True),
    ]
    best = []
    for d, k, low in cols:
        vals = [d[m][k] for m in METHODS if m in d]
        best.append(min(vals) if low else max(vals))

    def cell(d, m, k, b, ci=False):
        if m not in d:
            return "--"
        v = d[m][k]
        txt = ("%d" % round(100 * v)) if k == "ood_crash" else ("%.1f" % (100 * v))
        if ci and d[m].get("test_episodes", 0) > 0:
            txt += "{\\scriptsize$\\pm$%.1f}" % (100 * d[m]["test_post_ci"])
        return "\\textbf{%s}" % txt if abs(v - b) < 1e-12 else txt

    out = ["% generated by figures_scripts/tracking_table.py; do not edit",
           "\\begin{tabular}{@{}llrrrrrrr@{}}", "\\toprule",
           " & & \\multicolumn{4}{c}{Combination 1: residual on controller} & \\multicolumn{3}{c}{Combination 2: controller gains} \\\\",
           "\\cmidrule(lr){3-6}\\cmidrule(l){7-9}",
           "Method & Data & Before & After & OOD & OOD crash & Before & After & OOD \\\\",
           " & (ep.) & (cm) & (cm) & (cm) & (\\%) & (cm) & (cm) & (cm) \\\\", "\\midrule"]
    for m in METHODS:
        if m in GROUP:
            out.append("\\multicolumn{9}{@{}l}{\\emph{%s}} \\\\" % GROUP[m])
        data = res.get(m, gain.get(m, {})).get("test_episodes", 0)
        label = LABEL[m].replace("DR (no adaptation)", "DR (no adapt.)")
        cells = [cell(d, m, k, b, ci=(k == "test_post")) for (d, k, _), b in zip(cols, best)]
        out.append("%s & %s & %s \\\\" % (label, data if data else "0", " & ".join(cells)))
    out += ["\\bottomrule", "\\end{tabular}"]
    path = VENUE_DIR / "generated" / "tables" / "tracking.tex"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
